
import '@/registry/aodesu/theme.css';
import '@/registry/candy/theme.css';
import { ThemeProvider } from '@/registry/theme';
import type { Metadata } from "next";
import { Geist_Mono, Ubuntu, Work_Sans } from "next/font/google";
import "./globals.css";
import { Header } from './Header';

const geistSans = Work_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  variable: "--font-geist-ubuntu",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const workSans = Work_Sans({
  variable: "--work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const styleConfig = [
  { style: "aodesu", themes: ["dark", "light"] as const },
  { style: "candy", themes: ["light", "dark"] as const },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider isRoot styleConfig={styleConfig}>
      <html lang="es">
        <body
          className={`font-work-sans font-normal ${geistSans.variable} ${workSans.variable} ${ubuntu.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
