
import '@/registry/aodesu/theme.css';
import '@/registry/candy/theme.css';
import { ThemeProvider } from '@/registry/theme';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from './Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const styleConfig = [
  { style: "aodesu", themes: ["dark", "light"] as const },
  { style: "candy", themes: ["light"] as const },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider isRoot styleConfig={styleConfig}>
      <html lang="es">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Header />
            {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
